language: go
sudo: false
go:
  - 1.9.x
  - 1.10.x
  - 1.11.x

script:
    # build test for supported platforms
  - GOOS=linux go build
  - GOOS=darwin go build
  - GOOS=freebsd go build
  - GOOS=windows go build
  - GOARCH=386 go build

  - go test -v -cover -race
